const DESCRIPTOR_SIZE = 3;
const ADDRESS_SIZE = 20;
const SEED_SIZE = 48;
const EXTENDED_SEED_SIZE = DESCRIPTOR_SIZE + SEED_SIZE;

module.exports = {
  DESCRIPTOR_SIZE,
  ADDRESS_SIZE,
  SEED_SIZE,
  EXTENDED_SEED_SIZE,
};
